api-moudle: ygosvr

server:
  port: 9800

spring:
  profile:
    active: default
  application:
    name: ygosvr

fpweb:
  profile:
    active: default
  application:
    name: ygosvr

logging:
  level:
    root: info


database:
  host: localhost
  # host: mysqlserver
  port: 3306
  user: root
  password: root